### ISSUE TITLE
Issue running example code

### ISSUE THREAD

**Issue by kieroneil** [drsimonj/pipelearner#4]
I have another issue.  This looks to be triggered by the `contains("rsquare"))` part.
> results %>%
+     add_rsquare() %>% 
+     select(cv_pairs.id, contains("rsquare")) %>% 
+     gather(source, rsquare, contains("rsquare")) %>%
+     mutate(source = gsub("rsquare_", "", source)) %>% 
+     ggplot(aes(cv_pairs.id, rsquare, color = source)) +
+     geom_point() +
+     labs(x = "Fold", y = "R Squared")
Error in .p(.x[[i]], ...) : argument ".y" is missing, with no default
> traceback()
20: .p(.x[[i]], ...)
19: isTRUE(.p(.x[[i]], ...))
18: some(.x, identical, .y)
17: contains("rsquare")
16: eval(expr, envir, enclos)
15: eval(x$expr, data, x$env)
14: FUN(X[[i]], ...)
13: lapply(x, lazy_eval, data = data)
12: lazyeval::lazy_eval(args, names_list)
11: select_vars_(names(.data), dots)
10: select_.data.frame(.data, .dots = lazyeval::lazy_dots(...))
9: select_(.data, .dots = lazyeval::lazy_dots(...))
8: select(., cv_pairs.id, contains("rsquare"))
7: function_list[[i]](value)
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(expr, envir, enclos)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq` (`_lhs`)), env, env))
1: results %>% add_rsquare() %>% select(cv_pairs.id, contains("rsquare")) %>% 
       gather(source, rsquare, contains("rsquare")) %>% mutate(source = gsub("rsquare_", 
       "", source)) %>% ggplot(aes(cv_pairs.id, rsquare, color = source))
> 
What do you think is causing this?`

**Comment by kieroneil** [comment]
Nevermind, it starting working.

Consider this issue closed.

**Comment by neilfws** [comment]
For anyone else wondering, the issue here is that both `dplyr` and `purrr` have a `contains()` function. The error comes from `purrr` but the `select` should be using `dplyr::contains`. If both packages are loaded, try:

`results %>% dplyr::select(cv_pairs.id, dplyr::contains("rsquare"))`
