### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by VladPerervenko** [drsimonj/pipelearner#5]
````{r grid}
pl <- d %>% pipelearner(rpart, am ~ .,
                        minsplit = c(2, 20),
                        maxdepth = c(2, 5),
                        xval     = c(5, 10))
pl %>%
  learn() %>% 
  mutate(
    minsplit = map_dbl(params, "minsplit"),
    maxdepth = map_dbl(params, "maxdepth"),
    xval     = map_dbl(params, "xval"),
    accuracy_train = pmap_dbl(list(fit, train, target), accuracy),
    accuracy_test  = pmap_dbl(list(fit, test,  target), accuracy)
  ) %>% select(minsplit, maxdepth, xval, contains("accuracy"))`
Error in select(., minsplit, maxdepth, xval, contains("accuracy")) : 
  unused arguments (minsplit, maxdepth, xval, contains("accuracy"))

R3.3.2/Win7

**Comment by VladPerervenko** [comment]
`> tidyverse_conflicts()
Conflicts with tidy packages -----------------------
filter():     dplyr, stats
is_formula(): purrr, lazyeval
lag():        dplyr, stats
select():     dplyr, MASS
slice():      dplyr, xgboost`
For _select()_ need to specifically address _dplyr::select()_
Best regards

**Comment by drsimonj** [comment]
Thanks for getting in touch. This wasn't a problem in my post because
there's no explicit `library(MASS)`. Perhaps you had called this previously?
Either way, glad you sorted it out :)

Also, this is not an issue for the pipelearner package, so I'm closing the issue.

Simon
