### ISSUE TITLE
Using pipelearner in functions where "data =" is required

### ISSUE THREAD

**Issue by neilfws** [drsimonj/pipelearner#6]
I ran into an issue using `gam` from the `mcgv` package with pipelearner. To illustrate, `lm` can be used like this:

```
iris %>%
  lm(Sepal.Length ~ Sepal.Width, .)
```

and so can be piped into pipelearner:

```
iris %>%
  pipelearner(lm, Sepal.Length ~ Sepal.Width) %>%
  learn()
```

However, `gam` requires "data = " explicitly. The analogous expression to `lm` fails:

```
iris %>%
  gam(Sepal.Length ~ s(Sepal.Width), .)
Error in eval(expr, envir, enclos) : object 'Sepal.Length' not found

iris %>%
  pipelearner(gam, Sepal.Length ~ s(Sepal.Width)) %>%
  learn()
Error in eval(expr, envir, enclos) : object 'Sepal.Length' not found
```

This works:

```
iris %>%
  gam(Sepal.Length ~ s(Sepal.Width), data = .)
```

Is there a syntax which will allow pipelearner to run `gam`, or does pipelearner require modification?

**Comment by drsimonj** [comment]
Thanks @neilfws 
I've made an adjustment to `learn()` that I think was causing the problem. Please reinstall pipelearner from GitHub and try again.

**Comment by neilfws** [comment]
That fix seems to work, thanks!

I think something similar is also required for `predict.gam` to work in the modified `r_square` function, _i.e._:

```
  residuals <- predict(model, as.data.frame(data)) - actual
```

**Comment by drsimonj** [comment]
Great. Thanks for testing.

And, yes, often you need to convert resample objects with `as.data.frame()` like that. It's a worthy price to pay given the conveniences that resample objects offer in this context. E.g., see [docs for the `resample()`](https://github.com/hadley/modelr/blob/master/R/resample.R).
