### ISSUE TITLE
Add additional cross validation methods

### ISSUE THREAD

**Issue by wdearden** [drsimonj/pipelearner#8]
The functions in [resamplr](https://github.com/jrnold/resamplr) also use modelr::resample objects and includes all cross validation methods from scikit-learn.

It looks like learn_cvpairs can be written the same way as learn_models with arbitrary cross validation functions as long as the cross validation function returns a df with train, test, and .id columns (which is the case with resamplr).

**Comment by drsimonj** [comment]
Really nice idea! There are some other major things I want to fix, so this will be a good one to include in my next major rework. I noticed you forked the project. Are you considering submitting a PR?

**Comment by wdearden** [comment]
Sorry, didn't mean to hit "close issue". 

Sure, I can do it. FYI I'm thinking something along these lines:

```
learn_cvpairs.pipelearner <- function(pl, .f = ~ modelr::crossv_mc(~, n = 1), ...) {
  pl$cv_pairs <- purrr::invoke(.f, data = pl$data, ...)
  pl
}
```

Unfortunately `crossv_mc` does not have a default for n so it probably needs to look a little ugly like that in order to have a default function.
